package application.view.controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Button;
import javafx.scene.layout.HBox;
import javafx.scene.control.TextField;
import javafx.event.ActionEvent;
import javafx.scene.control.Label;
import javafx.scene.control.PasswordField;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.VBox;
import java.io.IOException;
import java.net.URL;
import java.sql.SQLException;
import java.util.ResourceBundle;
import application.customcls.User;
import application.DB.UserTable;
import javafx.scene.control.Alert;
import javafx.fxml.Initializable;

public class LoginController implements Initializable{ 
	@FXML
	private BorderPane border_pane;
	@FXML
	private VBox left_pane;
	@FXML
	private Label main_menu;
	@FXML
	private Label place_order;
	@FXML
	private Label collect_order;
	@FXML
	private Label cancel_order;
	@FXML
	private Label view_order;
	@FXML
	private Label export_all_order;
	@FXML
	private VBox center_pane;
	@FXML
	private TextField username;
	@FXML
	private PasswordField pwd;
	@FXML
	private Button login;
	@FXML
	private Label new_acct2;
	@FXML
	private Label msg_area;
	@FXML
	private HBox top_pane;
	@FXML
	private Label acct;
	@FXML
	private Label new_acct;
	@FXML
	private Label sign_in;
	
	//private User login_user;

	
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
	}	
	// Event Listener on Label[#main_menu].onMouseClicked
	@FXML
	public void lb_main_menu(MouseEvent event) {
		//go to Main Menu page
        try {
        	BorderPane parentContent = FXMLLoader.load(getClass().getResource(("/application/view/fxml/MainMenu.fxml")));
        	border_pane.getChildren().setAll(parentContent);
        }catch(IOException e){
            System.out.println(e);
        }    			
	}
	// Event Listener on Label[#place_order].onMouseClicked
	@FXML
	public void lb_place_order(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Label[#collect_order].onMouseClicked
	@FXML
	public void lb_collect_order(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Label[#cancel_order].onMouseClicked
	@FXML
	public void lb_cancel_order(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Label[#view_order].onMouseClicked
	@FXML
	public void lb_view_order(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Label[#export_all_order].onMouseClicked
	@FXML
	public void lb_export_all_order(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#login].onAction

	@FXML
	public void bt_login(ActionEvent event) throws SQLException{
		String user_name=username.getText();
        String user_pwd=pwd.getText();
        // check is existing user
        User usr = new User(null, user_name, user_pwd, null, null, null, 0.0, null, null);
        boolean check_user=UserTable.chkUserPwd(usr);
        // existing user
        if(check_user){
			// set user name
    		User usr_holder = User.getInstance();
            usr_holder.setUsername(user_name);
        	// check is VIP user
        	boolean check_vip = UserTable.chkVIP(user_name);
    		if (check_vip) {
    			//go to Main Menu page
                try {
                	BorderPane parentContent = FXMLLoader.load(getClass().getResource(("/application/view/fxml/MainMenu.fxml")));
                	border_pane.getChildren().setAll(parentContent);
                }catch(IOException e){
                    System.out.println(e);
                }    			
    		} else {
    			//go to VIP page
                try {
                	BorderPane parentContent = FXMLLoader.load(getClass().getResource(("/application/view/fxml/VIP.fxml")));
                	border_pane.getChildren().setAll(parentContent);
                }catch(IOException e){
                    System.out.println(e);
                }
    		}
        }else{
           	// input fields validation - wrong user name or password
            Alert msg=new Alert(Alert.AlertType.ERROR);
            msg.setTitle("Login Failed");
            msg.setHeaderText("Login Failed");
            msg.setContentText("Wrong Username or Password. Please re-try or register if you don't have an account.");            
            msg.showAndWait();
        }
	}
	// Event Listener on Label[#new_acct2].onMouseClicked
	@FXML
	public void lb_new_acct2(MouseEvent event) {
        try {
        	BorderPane parentContent = FXMLLoader.load(getClass().getResource(("/application/view/fxml/NewAcct.fxml")));
        	border_pane.getChildren().setAll(parentContent);
        }catch(IOException e){
            System.out.println(e);
        }
	}
	// Event Listener on Label[#msg_area].onMouseClicked
	@FXML
	public void msg_area(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Label[#acct].onMouseClicked
	@FXML
	public void lb_acct(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Label[#new_acct].onMouseClicked
	@FXML
	public void lb_new_acct(MouseEvent event) {
        try {
        	BorderPane parentContent = FXMLLoader.load(getClass().getResource(("/application/view/fxml/NewAcct.fxml")));
        	border_pane.getChildren().setAll(parentContent);
        }catch(IOException e){
            System.out.println(e);
        }
	}
	// Event Listener on Label[#sign_in].onMouseClicked
	@FXML
	public void lb_sign_in(MouseEvent event) {
        try {
        	BorderPane parentContent = FXMLLoader.load(getClass().getResource(("/application/view/fxml/Login.fxml")));
        	border_pane.getChildren().setAll(parentContent);
        }catch(IOException e){
            System.out.println(e);
        }
	}
}
